# Build Stage
FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY . .

WORKDIR /app/cmd/event-service

RUN go mod download && go build -o /go/bin/event-service

# Final Stage
FROM alpine:3.17

COPY --from=builder /go/bin/event-service /go/bin/event-service

ENTRYPOINT ["/go/bin/event-service"]
