version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile.api-gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
    depends_on:
      - booking-service
      - event-service
      - notification-service
    networks:
      - backend

  booking-service:
    build:
      context: .
      dockerfile: Dockerfile.booking-service
    container_name: booking_service
    networks:
      - backend

  event-service:
    build:
      context: .
      dockerfile: Dockerfile.event-service
    container_name: event_service
    networks:
      - backend

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile.notification-service
    container_name: notification_service
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
