# Build Stage
FROM golang:1.20-alpine AS builder

WORKDIR /app

COPY . .

WORKDIR /app/cmd/api-gateway    

RUN go mod download && go build -o /go/bin/api-gateway

# Final Stage
FROM alpine:3.17

COPY --from=builder /go/bin/api-gateway /go/bin/api-gateway

ENTRYPOINT ["/go/bin/api-gateway"]
